name: Version Bump
description: Bumps app version

inputs:
  working-directory:
    description: Path to cd into
    default: apps/mobile

  version-bump-type:
    description: Minor, Major or Patch
    default: none

runs:
  using: composite
  steps:
    - name: ⬆️ Bump App Version - Patch
      shell: bash
      if: ${{ inputs.versionBumpType == 'patch' }}
      working-directory: ${{ inputs.working-directory }}
      run: ./scripts/bump_version.sh -p

    - name: ⬆️ Bump App Version - Minor
      shell: bash
      if: ${{ inputs.versionBumpType == 'minor' }}
      working-directory: ${{ inputs.working-directory }}
      run: ./scripts/bump_version.sh -m

    - name: ⬆️ Bump App Version - Major
      shell: bash
      if: ${{ inputs.versionBumpType == 'major' }}
      working-directory: ${{ inputs.working-directory }}
      run: ./scripts/bump_version.sh -M

    - name: 👷 Commit Changes
      if: ${{ inputs.versionBumpType != 'none' }}
      uses: EndBug/add-and-commit@v9
      with:
        author_name: Dan Yalg
        author_email: dan@thecodingforge.com.au
        message: 'Automated Version Bump'
        add: 'apps/mobile/app.json'
